<#
.SYNOPSIS
  Walk an anti-adblock fallback chain and enumerate every bait host it offers,
  without naming any of them in advance.

.DESCRIPTION
  These loaders serve a script from a rotating host list and stop at the first
  host the browser's blocker does NOT cancel. So a single capture only ever
  reveals hosts up to the one that answers -- block that one, load again, and
  the next appears. This automates that walk.

  Nothing is hardcoded. Each round finds hosts by the loader's PATH, which does
  not rotate: /script/<base64(page hostname), padding stripped>.js. The token is
  derived from the target url, so a new site needs no configuration and a
  rotated host is found by shape rather than by name.

  Blocking is done with a PAC file pointed at an unroutable proxy, set in the
  CAPTURE CLONE's user.js only. That was chosen after measuring: in Chrome,
  neither CDP request interception (five abort modes) nor a declarativeNetRequest
  extension producing a genuine ERR_BLOCKED_BY_CLIENT made the loader advance.
  In Firefox a plain PAC connection failure does -- a run blocking the two hosts
  uBO let through walked past all four known hosts and revealed a fifth,
  poppyrimpace.com, which matched the operator fingerprint on every signal.

  ROUND 1 IS THE FAITHFUL CAPTURE: no PAC, so it shows what a normal visitor
  gets. Later rounds are deliberately distorted and exist only to enumerate. The
  round-1 capture is what gets left in place for the pipeline.

.EXAMPLE
  powershell -ExecutionPolicy Bypass -File C:\nwss-har\win-bait-walk.ps1
#>

param(
  [string[]]$Urls,
  [string]$TargetsFile = "",
  [string]$OutDir = "C:\nwss-har",
  [string]$Name = "capture",
  [int]$SecondsPerUrl = 20,
  [int]$MaxRounds = 5,
  [string]$Detect = "",
  [string]$CaptureScript = "",
  [switch]$KeepPac
)

$ErrorActionPreference = 'Stop'
if (-not $CaptureScript) { $CaptureScript = Join-Path $PSScriptRoot "win-capture-scheduled.ps1" }
if (-not (Test-Path $CaptureScript)) { throw "capture script not found: $CaptureScript" }
if (-not $TargetsFile) { $TargetsFile = Join-Path $OutDir "targets.txt" }

# --- target ------------------------------------------------------------------
if (-not $Urls -or $Urls.Count -eq 0) {
  if (-not (Test-Path $TargetsFile)) { throw "No -Urls and no targets file at $TargetsFile" }
  $Urls = @(Get-Content $TargetsFile | ForEach-Object { $_.Trim() } |
            Where-Object { $_ -and -not $_.StartsWith("#") })
}
if (-not $Urls -or $Urls.Count -eq 0) { throw "No target urls" }
$targetHost = ([uri]$Urls[0]).Host

# The loader path is base64 of the page hostname with '=' padding stripped --
# derived, never configured, so it follows the site rather than a host list.
if (-not $Detect) {
  $token = [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($targetHost)) -replace '=+$',''
  $Detect = "uri=https?://([^/ ]+)/script/$([regex]::Escape($token))\.js"
  Write-Host "  target  : $targetHost"
  Write-Host "  token   : $token   (base64 of the hostname)"
} else {
  Write-Host "  target  : $targetHost"
  Write-Host "  detect  : $Detect  (supplied)"
}

$profileDir = Join-Path $OutDir "capture-profile"
$userJs     = Join-Path $profileDir "user.js"
$pacFile    = Join-Path $OutDir "$Name-bait.pac"

# Registrable domain, good enough for the .com/.cc/.net hosts these use. A
# PAC blocks the root and every subdomain, since the shards live on
# 0.stg.<root> .. 9.stg.<root>.
function Get-Root([string]$h) {
  $p = $h.Split('.')
  if ($p.Count -le 2) { return $h }
  return ($p[-2..-1] -join '.')
}

function Write-Pac([string[]]$roots) {
  $list = ($roots | ForEach-Object { '"' + $_ + '"' }) -join ', '
  @"
// generated by win-bait-walk.ps1 -- blocks discovered bait hosts so the
// loader is forced to offer the next one in its list.
function FindProxyForURL(url, host) {
  var baits = [$list];
  for (var i = 0; i < baits.length; i++) {
    if (host === baits[i] || host.indexOf("." + baits[i]) === host.length - baits[i].length - 1) {
      return "PROXY 127.0.0.1:1";   // nothing listens -> connection refused
    }
  }
  return "DIRECT";
}
"@ | Set-Content -LiteralPath $pacFile -Encoding ASCII
}

function Set-PacPrefs {
  Remove-PacPrefs
  $pacUrl = "file:///" + ($pacFile -replace '\\','/')
  Add-Content -LiteralPath $userJs -Value @(
    'user_pref("network.proxy.type", 2);',
    "user_pref(`"network.proxy.autoconfig_url`", `"$pacUrl`");"
  )
}

function Remove-PacPrefs {
  if (-not (Test-Path $userJs)) { return }
  $kept = Get-Content -LiteralPath $userJs | Where-Object { $_ -notmatch 'network\.proxy' }
  Set-Content -LiteralPath $userJs -Value $kept
}

# Pull every host that served the loader path out of a capture family.
function Get-BaitHosts([string]$base) {
  $hits = Select-String -Path "$base*.moz_log" -Pattern $Detect -AllMatches -ErrorAction SilentlyContinue
  if (-not $hits) { return @() }
  @($hits | ForEach-Object { $_.Matches } | ForEach-Object { $_.Groups[1].Value } | Sort-Object -Unique)
}

# --- the walk ----------------------------------------------------------------
$blocked = New-Object System.Collections.Generic.List[string]
$found   = New-Object System.Collections.Generic.List[string]
$round   = 0
try {
  while ($round -lt $MaxRounds) {
    $round++
    $roundName = if ($round -eq 1) { $Name } else { "$Name-r$round" }
    if ($round -eq 1) {
      Remove-PacPrefs                      # round 1 is the faithful capture
      Write-Host "`n  round $round : no blocks (what a normal visitor sees)"
    } else {
      Write-Pac $blocked.ToArray()
      Set-PacPrefs
      Write-Host "`n  round $round : blocking $($blocked.Count) host(s): $($blocked -join ', ')"
    }

    & powershell.exe -NoProfile -ExecutionPolicy Bypass -File $CaptureScript `
        -Urls $Urls -OutDir $OutDir -Name $roundName -SecondsPerUrl $SecondsPerUrl | Out-Null
    if ($LASTEXITCODE -ne 0) { Write-Host "    capture failed; stopping"; break }

    $hosts = Get-BaitHosts (Join-Path $OutDir "$roundName.log")
    if (-not $hosts -or $hosts.Count -eq 0) { Write-Host "    no loader urls in this capture; stopping"; break }

    $newRoots = @()
    foreach ($h in $hosts) {
      if (-not $found.Contains($h)) { $found.Add($h) }
      $r = Get-Root $h
      if (-not $blocked.Contains($r)) { $blocked.Add($r); $newRoots += $r }
    }
    Write-Host "    hosts serving the loader: $($hosts -join ', ')"
    if ($newRoots.Count -eq 0) { Write-Host "    nothing new -- the list is exhausted"; break }
    Write-Host "    NEW: $($newRoots -join ', ')"

  }
} finally {
  if (-not $KeepPac) { Remove-PacPrefs; Remove-Item -LiteralPath $pacFile -Force -ErrorAction SilentlyContinue }
  # Only round 1 is a faithful capture; rounds 2+ are deliberately distorted and
  # are scratch. Cleaning them HERE rather than inside the loop matters: the loop
  # exits by break on "nothing new", so an in-loop cleanup never ran for the last
  # round and left its whole family behind.
  Get-ChildItem (Join-Path $OutDir "$Name-r*.log*") -ErrorAction SilentlyContinue |
    Remove-Item -Force -ErrorAction SilentlyContinue
  Get-ChildItem (Join-Path $OutDir "$Name-r*-runs.log") -ErrorAction SilentlyContinue |
    Remove-Item -Force -ErrorAction SilentlyContinue
}

# --- report ------------------------------------------------------------------
$roots = @($blocked | Sort-Object -Unique)
Write-Host "`n  === bait hosts enumerated in $round round(s) ==="
foreach ($r in $roots) {
  $ns = ""
  try { $ns = (Resolve-DnsName -Name $r -Type NS -ErrorAction SilentlyContinue |
               Where-Object { $_.NameHost } | ForEach-Object { $_.NameHost } | Sort-Object) -join ' ' } catch { }
  # The operator fingerprint: all known bait domains sit on one Cloudflare
  # account, while unrelated ad domains on the same pages do not.
  $fp = if ($ns -match 'houston\.ns\.cloudflare\.com' -and $ns -match 'veda\.ns\.cloudflare\.com') { "fingerprint MATCH" } else { "fingerprint differs" }
  Write-Host ("    {0,-24} {1}" -f $r, $fp)
  if ($ns) { Write-Host ("        ns: {0}" -f $ns) }
}
$outFile = Join-Path $OutDir "$Name-baits.txt"
$roots | Set-Content -LiteralPath $outFile -Encoding ASCII
Write-Host "`n  written: $outFile"
Write-Host "  capture kept: $(Join-Path $OutDir "$Name.log.moz_log")  (round 1, undistorted)"
